config/routes.rb
Fasleep::Application.routes.draw do
  get "site/ceshi",:as => :ceshi 

  get "site/fenxi"

  resources :surveys

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  attr_accessible :answer, :email

 



	def method_missing(method_name, *args, &block)
	  # delegate to superclass if you're not handling that method_name
	  return super unless /^answer_(.*)(=?)/ =~ method_name
	  # after match we have attribute name in $1 captured group and '' or '=' in $2
	 
	end
end

app/models/survey/questions.rb
#encoding:utf-8


module Questions

	

	def self.data
		@data ||= begin
			[
				{
					'q' => '我的性别是',
					'a' => %w(男 女)
				},

				{
					'q' => '我的年龄是',
					'a' => %w(30岁以下 30-45岁 45-60岁 60岁以上)
				},

				{
					'q' => '我每天晚上的睡眠时间为',
					'a' => %w(少于6小时 6-8小时 8-9小时 9小时以上)
				},

				{
					'q' => '关于入睡，我的情况是',
					'a' => %w(经常入睡困难 偶尔入睡困难 入睡较快 入睡很快)
				},

				{
					'q' => '关于白天乏力、没有精神，我的情况是',
					'a' => %w(经常发生 偶尔产生 几乎没有 从来没有)
				},

				{
					'q' => '关于晚上睡觉时的表现，我的表现是',
					'a' => %w(每晚醒几次 偶尔醒来 几乎不醒 从来不醒)
				},

				{
					'q' => '关于内心状态，我的情况是',
					'a' => %w(经常着急 偶尔着急 不着急 从不着急)
				},

				{
					'q' => '关于睡觉时做梦，我的情况是',
					'a' => %w(每晚做梦 偶尔做梦 很少做梦 几乎不做梦)
				},

				{
					'q' => '关于头发，我的情况是',
					'a' => %w(经常掉 偶尔掉 很少掉 几乎不掉)
				},

				{
					'q' => '关于气色，我的情况是',
					'a' => %w(很不好 不好 一般 很好)
				},

				{
					'q' => '关于头晕，我的情况是',
					'a' => %w(经常发生 偶尔发生 很少发生 几乎不发生)
				},

				{
					'q' => '关于记忆，我的情况是',
					'a' => %w(经常健忘 偶尔健忘 记忆力还行 记忆力很好)
				},

				{
					'q' => '(本题只针对女性) 关于例假，我的情况是',
					'a' => %w(很不正常 不正常 正常 很正常)
				},

				{
					'q' => '关于手脚的温度，我的情况是',
					'a' => %w(总是手脚冰凉  经常手脚冰凉 正常 很正常)
				},

				{
					'q' => '关于焦虑，我的情况是',
					'a' => %w(经常焦虑 偶尔出现 几乎没有 从来没有)
				},

				{
					'q' => '关于受惊吓，我的情况是',
					'a' => %w(很容易受惊吓 偶尔受到惊吓 几乎不受惊吓 从来不受惊吓)
				},

				{
					'q' => '我有以下一种或几种情况',
					'a' => %w(心脏病 高血压 已经怀孕 无)
				}
			]

		end

	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/site_controller.rb
require 'survey/questions'
class SiteController < ApplicationController
  def ceshi
  	@agent = request.env['HTTP_USER_AGENT']
  	@data = Questions.data
  	@survey = Survey.new
  end

  def fenxi
  	
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	def create
		#answers = params['survey']

		@type = get_types(params['survey'])

		render 'site/fenxi'
	end


	protected

	def get_types(_answers)
		scores = [4,3,1,0]

		answers = {}

		_answers.each do |k,v|
			answers[k] = v.to_i
		end

		#如果第17题选C，则输出：“您目前不适合在本场所进行相关的保健工作，请在适当的时候再来做保健。”否则，进行到下一步
		if answers['answer_16'] == 2
			type = type = "F-E1"
		#answers
		puts answers
		elsif answers['answer_0'] == 0 
			score_x =  scores[answers['answer_5']] + scores[answers['answer_6']] + scores[answers['answer_7']]  + scores[answers['answer_8']] + scores[answers['answer_9']]

			score_x = score_x * 5		


			score_y = scores[answers['answer_3']] +  scores[answers['answer_4']] + scores[answers['answer_5']] + scores[answers['answer_14']]  + scores[answers['answer_15']]
			score_y = score_y * 5	


			score_z = scores[answers['answer_2']] +  scores[answers['answer_10']] + scores[answers['answer_11']] + scores[answers['answer_13']] 
			score_z = score_z * 100 / 16	

			#get score
			max_score = score_x
			max_score = score_y if score_y > max_score
			max_score = score_z if score_z > max_score

		
			if max_score > 50

				if score_x == score_y && score_y == score_z && score_y == max_score
					if answers['answer_1'] > 1
						type = "F-3" 
					else
						type = "F-2"
					end
				elsif score_x == score_z && score_z == max_score
					if answers['answer_1'] > 1
						type = "F-3" 
					else
						type = "F-1"
					end

				#y=z
				elsif score_z == score_y  && score_y == max_score
					if answers['answer_1'] > 1
						type = "F-3" 
					else
						type = "F-2"
					end
				#x=y
				elsif score_x == score_y  && score_y == max_score

					type = "F-2"
				else
						type = "F-1" if max_score == score_x
						type = "F-2" if max_score == score_y
						type = "F-3" if max_score == score_z
				
				end

			elsif max_score > 25
				type = "F-5"
			else
				type = "F-E0"
			end

		#female
		else
			score_x = scores[answers['answer_5']] + scores[answers['answer_6']] + scores[answers['answer_7']]  + scores[answers['answer_8']] + scores[answers['answer_9']] + scores[answers['answer_12']]

			score_x = score_x * 100.0 / 24		


			score_y = scores[answers['answer_3']] +  scores[answers['answer_4']] + scores[answers['answer_5']] + scores[answers['answer_14']]  + scores[answers['answer_15']]
			score_y = score_y * 5	


			score_z = scores[answers['answer_2']] +  scores[answers['answer_10']] + scores[answers['answer_11']] + scores[answers['answer_13']] 
			score_z = score_z * 100.0 / 16	

			#get score
			max_score = score_x
			max_score = score_y if score_y > max_score
			max_score = score_z if score_z > max_score

			if max_score > 50
				if score_x == score_y && score_y == score_z && score_y == max_score
					if answers['answer_1'] > 1
						type = "F-3" 
					else
						type = "F-1"
					end
				elsif score_x == score_z && score_z == max_score
					if answers['answer_1'] > 1
						type = "F-3" 
					else
						type = "F-1"
					end

				#y=z
				elsif score_z == score_y  && score_y == max_score
					if answers['answer_1'] > 1
						type = "F-3" 
					else
						type = "F-2"
					end
				#x=y
				elsif score_x == score_y  && score_y == max_score
					type = "F-1"
				else
						type = "F-1" if max_score == score_x
						type = "F-2" if max_score == score_y
						type = "F-3" if max_score == score_z
				end
			elsif max_score > 25
				type = "F-5"
			else
				type = "F-E0"
			end

		end
		
		return type
	end
end
	

=begin
1.肝郁血虚型：女性居多。

典型症状：脾气急（7），小心眼，想得到，管得多，睡觉轻（6），做梦多（8），兼有血虚的症状：气色差（10），月经不调（13），掉头发多（9）。

2.胆热痰湿型：男性居多，女性也不少，可以作为首选方

典型症状：入睡困难（4），易醒（6），白天乏力没精神（5），容易受惊吓感（16），抑郁焦虑（15）。

3.气虚血瘀型：老年人居多

典型症状：血液循环不好，脑供血不足（14），健忘（12），头晕（11），睡眠少（3）。

一、 针对选项进行赋值：A=4分，B=3分，C=1，D=0

二、 如果第17题选C，则输出：“您目前不适合在本场所进行相关的保健工作，请在适当的时候再来做保健。”否则，进行到下一步。

三、 对于男性，1的满分为20分，2的满分为20分，3的满分为16分

1. 把1对应的6，7，8，9，10得分相加，总和除以20乘以100得总分X

2. 把2对应的4，5，6，15，16得分相加，总和除以20乘以100得总分Y

3. 把3对应的3，11，12，14得分相加，总和除以16乘以100得总分Z

4. 对比X、Y、Z，取最大值，

1) 若最大值大于50，且对应的是X，则输出F-1方

2) 若最大值大于50，且对应的是Y，则输出F-2方

3) 若最大值大于50，且对应的是Z，则输出F-3方

4) 若最大值小于50且大于25，则输出F-5方

5) 若最大值小于25，则输出：“恭喜您！您暂时不需要在快睡好眠做保健！”

6) 若X=Y，则输出F-2方

7) 若Y=Z，当年龄选择在C或D时，则输出F-3方；当年龄选择在A或B时，则输出F-2方

8) 若X=Z，当年龄选择在C或D时，则输出F-3方；当年龄选择在A或B时，则输出F-1方

9) 若X=Y=Z，当年龄选择在C或D时，则输出F-3方；当年龄选择在A或B时，则输出F-2方

四、 对于女性，1的满分为24分，2的满分为20分，3的满分为16分

1. 把1对应的6，7，8，9，10，13得分相加，总和除以24乘以100得总分X

2. 把2对应的4，5，6，15，16得分相加，总和除以20乘以100得总分Y

3. 把3对应的3，11，12，14得分相加，总和除以16乘以100得总分Z

4. 对比X、Y、Z，取最大值，

a) 若最大值大于50，且对应的是X，则输出F-1方

b) 若最大值大于50，且对应的是Y，则输出F-2方

c) 若最大值大于50，且对应的是Z，则输出F-3方

d) 若最大值小于50且大于25，则输出F-5方

e) 若最大值小于25，则输出：“恭喜您！您暂时不需要在快睡好眠做保健！”

f) 若X=Y，则输出F-1方

g) 若Y=Z，当年龄选择在C或D时，则输出F-3方；当年龄选择在A或B时，则输出F-2方

h) 若X=Z，当年龄选择在C或D时，则输出F-3方；当年龄选择在A或B时，则输出F-1方

i) 若X=Y=Z，当年龄选择在C或D时，则输出F-3方；当年龄选择在A或B时，则输出F-1方。
=end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
#encoding:utf-8
module SiteHelper

	Letters = %w(A、 B、 C、 D、)

	def to_label(index,q)
		"#{index + 1}、 #{q}"
	end

	def to_collections(data_arrry)
		res = []

		data_arrry.each_with_index do |item,index|
			#res << [Letters[index]+item,index]
			res << [item,index]
		end
		res
	end
end

app/helpers/surveies_helper.rb
module SurveiesHelper
	
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>快睡好眠快速测试题</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densitydpi=device-dpi" />
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class='<%="font-large" if @agent=~/MicroMessenger/%>'>

<%= yield %>

</body>
</html>

app/views/site/ceshi.html.erb
<link href="/css/icheck/square/red.css" rel="stylesheet">
<script src="/js/icheck.min.js"></script>


<div class="container">
    <div class="row-fluid">
        <div class="col-md-12">
            <h2 class="text-center"> 快睡好眠快速测试题 </h2>
            
            <p class＝"lead"> 尊敬的朋友：</p>
            <div style="text-indent:2em">
                <p class＝"lead">    欢迎您来到快睡好眠科技有限公司！为了使您不虚此行，请针对以下项目选择出您认为和您的现状最接近的答案。</p>
            </div>
                

            <%= simple_form_for @survey ,:html => { :class => 'form-inline' ,:id=>'valid-form'} do |f| %>

                <%@data.each_with_index do |item, index|%>
                    <%= f.input "answer_#{index}".to_sym,  as: :radio_buttons, collection: to_collections(item['a']), label: to_label(index,item['q']) %>
                    <br>
                <%end%>

               <div class="text-center lead">
                    <%= f.button :submit,:value=>'提交',:class=>'btn btn-primary' %>
               </div>
            <% end %>

        </div>
    </div>
</div>



<script type="text/javascript">
            // Validation
            $(function() {

                


                $('.controls').addClass('row-fluid clearfix');
                $('label.radio').addClass('col-xs-12 col-md-2');
                $('.survey_answer_12').hide();

                <%if @agent=~/MicroMessenger/ %>
                             $('input').iCheck({
                                checkboxClass: 'icheckbox_square-red',
                                radioClass: 'iradio_square-red',
                                increaseArea: '200%' // optional
                              });
                <%end%>

                $(".survey_answer_0 input[type='radio']").click(function(){
                    //male
                    if( $(this).val() == 0 ){
                        $('.survey_answer_12').hide();
                    }
                    //female
                    else{
                        $('.survey_answer_12').show();
                    }
                })

                $('.controls').mouseover(function(){
                    $(this).css('background-color','#DFF7D9');
                }).mouseout(function(){
                    $(this).css('background-color','none');
                })
                // Validation
                $("#valid-form").validate({

                    // Rules for form validation
                    rules : {
                        <%@data.count.times do |i| %>
                            '<%= "survey[answer_#{i}]" %>'  : {
                                required : true,
                            },
                        <%end%>
                    },


                    // Messages for form validation
                    messages : {
                        <%@data.count.times do |i| %>
                            '<%= "survey[answer_#{i}]" %>'  : {
                                required : '您忘记选择这项啦！',
                            },
                        <%end%>

                    },
                    // Ajax form submition
                    submitHandler : function(form) {
                        $(form).ajaxSubmit({
                            success : function() {
                                $("#valid-form").addClass('submited');
                            }
                        });
                    },

                    // Do not change code below
                    errorPlacement : function(error, element) {
                        error.insertAfter(element.parent().parent().last());
                    }
                });


            });
        </script>

app/views/site/fenxi.html.erb
<div class="container" >
	<div class="lead text-center" style="padding-top:80px;" >

		<% if @type == "F-E0" %>
			恭喜您！您暂时不需要在快睡好眠做保健！
		<% elsif @type == "F-E1" %>
			您目前不适合在本场所进行相关的保健工作，请在适当的时候再来做保健。
		<% else %>

			<big><strong >根据您的体质，快睡好眠  <%= @type %>  方案适合您</strong> </big> 
		<% end %>

		<div class="text-center" style="padding-top:20px;" >
			<a class="btn btn-success" href="<%= ceshi_path %>">  重新测试 </a>
		</div>
	</div>

</div>